base/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from base import views

app_name = "base"

urlpatterns = [
    url('login', views.LoginView.as_view(), name='login'),
    url('logout', views.LogoutView.as_view(), name='logout'),
    url('', views.BaseView.as_view(), name='base'),
]

contribution/urls.py
from django.conf.urls import include, url
from contribution import views

app_name = "contribution"

urlpatterns = [
    url(r'vote/(?P<id_contribution>[0-9]+)/(?P<value>[0-1])$', views.VoteContributionView.as_view(), name='vote_contribution'),
    url(r'change/mode/(?P<value>[0-1])$', views.ChangeModeView.as_view(), name='change-mode'),
    url(r'user/page/(?P<id_user>[0-9]+)$', views.UserPageView.as_view(), name='user_page'),
    url(r'take/comments/(?P<id_contribution>[0-9]+)$', views.DownloadCommentsView.as_view(), name='download_comments'),
    url(r'(?P<id_contribution>[0-9]+)$', views.SingleContributionView.as_view(), name='single_contribution'),
    url(r'all$', views.AllContributionsView.as_view(), name='all_contributions'),
    url(r'information$', views.InformationPageView.as_view(), name='information_page'),
    url(r'^$', views.HomeView.as_view(), name='home'),
]

contribution_project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from base import urls as urls_base
from contribution import urls as urls_contribution

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('base/', include(urls_base, namespace='base')),
    url(r'', include(urls_contribution, namespace='contributions')),
]

base/models.py
from django.db import models

from django.conf import settings


class UserConf(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='configuration')
    dark_mode = models.BooleanField(null=False)

base/views.py
from django.shortcuts import render, redirect, reverse

from django.http import JsonResponse
from django.http import HttpResponse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from contribution.models import Contribution


# Create your views here.
class BaseView(View):
    context = {}
    template_name = 'base/base.html'
    xml_template_name = 'base/xml/base.xml'
    redirect = False
    dir_redirect = ''
    type_response = ''

    def dispatch(self, request, *args, **kwargs):
        self.context = {}
        if 'format' in request.GET:
            format = request.GET['format']
            if format == 'xml':
                self.type_response = 'xml'
            if format == 'json':
                self.type_response = 'json'


        contributions = Contribution.objects.filter(author__id=request.user.id).exclude(source=None)[::-1][0:3]
        last_access = []
        for contribution in contributions:
            last_access.append(contribution.source)
        
        
        self.context['last_access'] = last_access

        if request.user.is_authenticated and request.user.configuration.dark_mode:
            self.context['dark_mode'] = True

        # raise Exception(self.context)
        return super(BaseView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.base_get(request, *args, **kwargs)
        if request.user.is_authenticated:
            self.auth_get(request, *args, **kwargs)

        # first we redirect
        if self.redirect:
            return redirect(self.dir_redirect)

        # raise Exception(self.context)
        # Before check if it's a special render
        if self.type_response == 'xml':
            return render(request, self.xml_template_name, self.context, content_type='text/xml')
        elif self.type_response == 'json':
            return JsonResponse(self.context)

        # Here we render a single html
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.base_post(request, *args, **kwargs)

        if request.user.is_authenticated:
            self.auth_post(request, *args, **kwargs)

        # first we redirect
        if self.redirect:
            return redirect(self.dir_redirect)

        # Before check if it's a special render
        if self.type_response == 'xml':
            return render(request, self.xml_template_name, self.context)
        elif self.type_response == 'json':
            return JsonResponse(self.context)

        # Here we render a single html
        return render(request, self.template_name, self.context)

    def auth_get(self, request, *args, **kwargs):
        pass

    def base_get(self, request, *args, **kwargs):
        pass

    def auth_post(self, request, *args, **kwargs):
        pass

    def base_post(self, request, *args, **kwargs):
        pass

class LoginView(View):
    def post(self, request, *args, **kwargs):
    
        user = authenticate(request, username=request.POST['user'], password=request.POST['pass'])
        # Correct users and password
        if user is None:
            messages.error(request, 'Usuario erroneo y password no coinciden.')
        else:
            login(request, user)

        return redirect(request.POST['redirect'])

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('contributions:home'))

templates/base/base.html
<!doctype html>
<html lang="es">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lo Visto</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'vendor/fonts/circular-std/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'libs/css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'vendor/fonts/fontawesome/css/fontawesome-all.css' %} ">
    <link rel="icon"href="{% static 'favicon.ico' %}">
    {% if dark_mode %}
        <link rel="stylesheet" href="{% static 'libs/css/dark-style.css' %} ">
    {% endif %}
</head>

<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
         <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
         <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                <a class="navbar-brand" href="{% url 'contributions:home'%}">{% block title %}LO VISTO{% endblock %}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top">
                        {% if user.is_authenticated %}
                            <li class="nav-item" style="margin-right: 10px;">
                                {% if dark_mode %}
                                    <a href="{% url 'contributions:change-mode' value=0 %}" class="btn btn-info"> Cambiar a modo claro</a>
                                {% else %}
                                    <a href="{% url 'contributions:change-mode' value=1 %}" class="btn btn-info">Cambiar a modo oscuro</a>
                                {% endif %}

                            </li>
                            <li class="nav-item">
                                <h5> Logueado como {{ user.username }}</h5>
                            </li>
                            <li class="nav-item">
                                <a  style="margin: 5px;" href="{% url 'base:logout' %}" class="btn btn-danger">Logout</a>
                            </li>
                          
                        {% else %}

                            <form method="post" action="{% url 'base:login'%}">
                                <input type="hidden" name="redirect" value="{{ request.get_full_path }}">
                                {% csrf_token %}
                                <li class="nav-item">


                                    <div class="top-search-bar" style="float: right">
                                        <button class="form-control" type="submit"> Login </button>
                                    </div>
                                    <div class="top-search-bar" style="float: right">
                                        <input class="form-control" type="password" placeholder="Contraseña" id="pass" name="pass">
                                    </div>
                                    <div class="top-search-bar" style="float: right">
                                        <input class="form-control" type="text" placeholder="usuario" id="user" name="user">
                                    </div>

                                </li>

                            </form>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
      <div class="nav-left-sidebar sidebar-dark">
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:home' %}">Inicio</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:home' %}?format=xml">Inicio en xml</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:home' %}?format=json">Inicio en json</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:all_contributions' %}">Ver todas las contribuciones</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:all_contributions' %}?format=xml">Ver todas las contribuciones en xml</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:all_contributions' %}?format=json">Ver todas las contribuciones en json</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:information_page' %}">Información</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:information_page' %}?format=xml">Información en xml</a>
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link" href="{% url 'contributions:information_page' %}?format=json">Información en json</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- end left sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- wrapper  -->
        <!-- ============================================================== -->
        <div class="dashboard-wrapper">
            <div class="container-fluid dashboard-content">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12" style="min-height: 90%">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                    {{ message }}
                                    <a href="#" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></a>
                                </div>
                            {% endfor %}
                        {% endif %}
                        {% block body %}sad {% endblock %}
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <div class="footer">
                Esta aplicación utiliza datos proporcionados por {% for access in last_access %} {{ access }}, {% endfor %} y más
            </div>
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->

    {% static 'vendor/jquery/jquery-3.3.1.min.js' %}
    <script src="{% static 'vendor/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'vendor/slimscroll/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'libs/js/main-js.js' %}"></script>
</body>

</html>