base/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from base import views

app_name = "base"

urlpatterns = [
    url('login', views.LoginView.as_view(), name='login'),
    url('logout', views.LogoutView.as_view(), name='logout'),
    url('', views.BaseView.as_view(), name='base'),
]

contribution/urls.py
from django.conf.urls import include, url
from contribution import views

app_name = "contribution"

urlpatterns = [
    url(r'vote/(?P<id_contribution>[0-9]+)/(?P<value>[0-1])$', views.VoteContributionView.as_view(), name='vote_contribution'),
    url(r'change/mode/(?P<value>[0-1])$', views.ChangeModeView.as_view(), name='change-mode'),
    url(r'user/page/(?P<id_user>[0-9]+)$', views.UserPageView.as_view(), name='user_page'),
    url(r'take/comments/(?P<id_contribution>[0-9]+)$', views.DownloadCommentsView.as_view(), name='download_comments'),
    url(r'(?P<id_contribution>[0-9]+)$', views.SingleContributionView.as_view(), name='single_contribution'),
    url(r'all$', views.AllContributionsView.as_view(), name='all_contributions'),
    url(r'information$', views.InformationPageView.as_view(), name='information_page'),
    url(r'^$', views.HomeView.as_view(), name='home'),
]

contribution_project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from base import urls as urls_base
from contribution import urls as urls_contribution

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('base/', include(urls_base, namespace='base')),
    url(r'', include(urls_contribution, namespace='contributions')),
]

contribution/models.py
import datetime

from django.db import models
from django.conf import settings
from contribution.handle_resources import HandleResources


class Contribution(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=500)
    html = models.TextField()
    description = models.TextField()
    date = models.DateTimeField()
    source = models.CharField(max_length=150, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='contributions')

    def get_contribution_formated(self, user_id):
        all_comments = self.comments.all().order_by('-date')
        all_comments_serializer = []
        for comment in all_comments:
            all_comments_serializer.append(comment.to_json())

        vote_user = None
        if self.votes.filter(user__id=user_id).first():
            vote_user = self.votes.filter(user__id=user_id).first().to_json()

        return {
            'id': self.id,
            'name': self.name,
            'url': self.url,
            'html': self.html,
            'description': self.description,
            'date': self.date,
            'author_id': self.author.id,
            'author_username': self.author.username,
            'like': self.votes.filter(value_vote=True).count(),
            'unlike': self.votes.filter(value_vote=False).count(),
            'user_voted': vote_user,
            'num_comments': len(all_comments_serializer)
        }

    def get_contribution_formated_comments(self, user_id):
        all_comments = self.comments.all().order_by('-date')
        all_comments_serializer = []
        for comment in all_comments:
            all_comments_serializer.append(comment.to_json())


        vote_user = None
        if self.votes.filter(user__id=user_id).first():
            vote_user = self.votes.filter(user__id=user_id).first().to_json()

        return {
            'id': self.id,
            'name': self.name,
            'url': self.url,
            'html': self.html,
            'description': self.description,
            'date': self.date,
            'author_id': self.author.id,
            'author_username': self.author.username,
            'like': self.votes.filter(value_vote=True).count(),
            'unlike': self.votes.filter(value_vote=False).count(),
            'user_voted': vote_user,
            'comments': all_comments_serializer,
            'num_comments': len(all_comments_serializer)
        }

    def get_contribution_formated_summary(self):
        return {
            'id': self.id,
            'name': self.name,
            'url': self.url
        }

    def to_json(self):
        return {
            'name': self.name,
            'url': self.url,
            'html': self.html,
            'description': self.description,
            'date': self.date,
            'author': {'username': self.author.username, 'id': self.author.id},
        }

    def save_contribution_with_resource(self, author):
        handle_resources = HandleResources()

        self.date = datetime.datetime.now()
        self.author = author
        result_handles = handle_resources.identify_resource(self.url)
        self.html = result_handles['html']
        self.source = result_handles['resource']
        self.save()


class Comment(models.Model):
    text = models.TextField()
    date = models.DateTimeField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    contribution = models.ForeignKey('Contribution', on_delete=models.CASCADE, related_name='comments')

    def get_comments_formated(self):
        return {
            'id': self.id,
            'text': self.text,
            'date': self.date,
            'id_contribution': self.contribution.id,
            'name_contribution': self.contribution.name,
            'url_contribution': self.contribution.url,
            # 'tiny_url_contribution': self.contribution.url[0:40]+'...'
        }

    def to_json(self):
        return {
            'text': self.text,
            'date': self.date.strftime("%Y-%m-%d %H:%M:%S"),
            'author': {'username': self.author.username, 'id': self.author.id},
            'contribution': self.contribution.to_json()
        }

    def save_comment(self, contribution, author):
        self.date = datetime.datetime.now()
        self.contribution = contribution
        self.author = author
        self.save()


class Vote(models.Model):
    contribution = models.ForeignKey(Contribution, on_delete=models.CASCADE, related_name='votes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='votes')
    value_vote = models.BooleanField()

    def get_vote_formated(self):
        return {
            'id': self.id,
            'value_vote': self.value_vote,
            'id_contribution': self.contribution.id,
            'name_contribution': self.contribution.name,
            'url_contribution': self.contribution.url,
            # 'tiny_url_contribution': self.contribution.url[0:40]+'...'
        }

    def to_json(self):
        return {
            'value_vote': self.value_vote,
            'user': {'username': self.user.username, 'id': self.user.id},
            'contribution': self.contribution.to_json()
        }

contribution/forms.py
from django.forms import ModelForm
from contribution.models import Contribution, Comment


class ContributionForm(ModelForm):
    class Meta:
        model = Contribution
        fields = ['name', 'url','description']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

contribution/views.py
from django.shortcuts import render, reverse
from base.views import BaseView

from contribution.models import Contribution, Comment, Vote
from contribution.forms import ContributionForm, CommentForm


class HomeView(BaseView):
    template_name = 'contribution/home.html'
    xml_template_name = 'contribution/xml/home.xml'

    def auth_get(self, request, *args, **kwargs):
        self.context['vote_user_id'] = request.user.id
        if not self.type_response:
            self.context['new_contribution_form'] = ContributionForm()

        contributions = Contribution.objects.filter(author__id=request.user.id)[::-1][0:5]
        final_contributions = []
        for contribution in contributions:
            final_contributions.append(contribution.get_contribution_formated_summary())
        self.context['last_user_contributions'] = final_contributions

    def base_get(self, request, *args, **kwargs):

        contributions = Contribution.objects.all()[::-1][0:10]
        final_contributions = []
        for contribution in contributions:
            final_contributions.append(contribution.get_contribution_formated(request.user.id))

        self.context['contributions'] = final_contributions

    def auth_post(self, request, *args, **kwargs):
        if not self.type_response:
            form = ContributionForm(request.POST or None, request.FILES or None)

            # check if form data is valid
            if form.is_valid():

                form.instance.save_contribution_with_resource(request.user)

    def base_post(self, request, *args, **kwargs):
        self.redirect = True
        self.dir_redirect = reverse('contributions:home')


class VoteContributionView(BaseView):
    def auth_get(self, request, *args, **kwargs):
        contribution = Contribution.objects.filter(id=kwargs['id_contribution']).first()
        if contribution:
            vote = Vote.objects.filter(contribution__id=kwargs['id_contribution'], user__id=request.user.id).first()
            value_vote = True if str(kwargs['value']) == str(1) else False
            if vote:
                if vote.value_vote != value_vote:
                    vote.value_vote = value_vote
                    vote.save()
            else:
                vote = Vote()
                vote.contribution = contribution
                vote.user = request.user
                vote.value_vote = value_vote
                vote.save()

    def base_get(self, request, *args, **kwargs):
        self.redirect = True
        self.dir_redirect = request.GET['redirect']


class ChangeModeView(BaseView):

    def auth_get(self, request, *args, **kwargs):

        value_mode = True if str(kwargs['value']) == str(1) else False
        request.user.configuration.dark_mode = value_mode
        request.user.configuration.save()

    def base_get(self, request, *args, **kwargs):
        self.redirect = True
        self.dir_redirect = reverse('contributions:home')


class SingleContributionView(BaseView):
    template_name = 'contribution/single_contribution.html'
    xml_template_name = 'contribution/xml/single_contribution.xml'

    def auth_get(self, request, *args, **kwargs):
        self.context['vote_user_id'] = request.user.id
        if not self.type_response:
            self.context['new_comment_form'] = CommentForm()

    def base_get(self, request, *args, **kwargs):
        contribution = Contribution.objects.filter(id=kwargs['id_contribution']).first()
        if contribution:
            self.context['contribution'] = contribution.get_contribution_formated_comments(request.user.id)
        else:
            self.redirect = True
            self.dir_redirect = reverse('contributions:home')

    def auth_post(self, request, *args, **kwargs):
        form = CommentForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form.instance.save_comment(self.context['contribution'], request.user)

    def base_post(self, request, *args, **kwargs):
        contribution = Contribution.objects.filter(id=kwargs['id_contribution']).first()
        self.redirect = True

        if contribution:
            self.context['contribution'] = contribution
            self.dir_redirect = reverse('contributions:single_contribution', kwargs={'id_contribution': contribution.id})
        else:
            self.dir_redirect = reverse('contributions:home')


class UserPageView(BaseView):
    template_name = 'contribution/user_page.html'
    xml_template_name = 'contribution/xml/user_page.xml'

    def auth_get(self, request, *args, **kwargs):
        # Taking votes with format
        votes = Vote.objects.filter(user__id=request.user.id)
        final_votes = []
        for vote in votes:
            final_votes.append(vote.get_vote_formated())
        # Taking all comment of user
        comments = Comment.objects.filter(author__id=request.user.id)
        final_comments = []
        for comment in comments:
            final_comments.append(comment.get_comments_formated())

        # Taking all contribution of user
        contributions = Contribution.objects.filter(author__id=request.user.id)
        final_contributions = []
        for contribution in contributions:
            final_contributions.append(contribution.get_contribution_formated_summary())

        self.context['votes'] = final_votes[::-1]
        self.context['comments'] = final_comments[::-1]
        self.context['contributions'] = final_contributions[::-1]

    def base_get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            self.redirect = True
            self.dir_redirect = reverse('contributions:home')


class AllContributionsView(BaseView):
    template_name = 'contribution/all_contrbutions.html'
    xml_template_name = 'contribution/xml/all_contrbutions.xml'

    def base_get(self, request, *args, **kwargs):
        contributions = Contribution.objects.all().order_by('-date')

        final_contributions = []
        for contribution in contributions:
            final_contributions.append(contribution.get_contribution_formated_summary())
        self.context['contributions'] = final_contributions


class InformationPageView(BaseView):
    template_name = 'contribution/information_page.html'
    xml_template_name = 'contribution/xml/information_page.xml'

    def base_get(self, request, *args, **kwargs):
        self.context['author'] = 'Desarrollado por Gonzalo López López'
        self.context['object'] = 'Este proyecto tiene como objetivo crear una comunidad de personas que compartan y comenten contenidos.'
        self.context['fuctionality'] = "Tenemos un listado de aportaciones hechas por la comunidad, esas aportaciones podrás votarlas y comentarlas, además de añadir nuevas aportaciones propias y hacerles un seguirmiento."

class DownloadCommentsView(BaseView):
    xml_template_name = 'contribution/xml/comments_single_contribution.xml'

    def base_get(self, request, *args, **kwargs):
        if not self.type_response:
            self.type_response = 'xml'

        contribution = Contribution.objects.filter(id=kwargs['id_contribution']).first()
        if contribution:
            self.context['comments'] = contribution.get_contribution_formated_comments(request.user.id)['comments']
        else:
            self.redirect = True
            self.dir_redirect = reverse('contributions:home')

templates/contribution/all_contrbutions.html
{% extends "base/base.html" %}

{% block body %}
<div class="row">
    <div class="col-12">
        {% for contribution in contributions %}
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'contributions:single_contribution' id_contribution=contribution.id %}">
                            <h3 class="card-title">{{ contribution.name }}</h3>
                        </a>
                        <a href="{{ contribution.url }}" class="btn btn-primary">{{ contribution.url }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
</div>
{% endblock body %}

templates/contribution/home.html
{% extends "base/base.html" %}

{% block body %}
    <div class="row">
        <div class="col-7">
            {% for contribution in contributions %}
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">
                                <a href="{% url 'contributions:single_contribution' id_contribution=contribution.id %}">
                                    {{ contribution.name }}
                                </a>
                                <span style="float: right"> {{ contribution.date |date:"d/m/Y H:i" }}</span>
                            </h3>
                            <a href="{{ contribution.url }}" class="btn btn-primary">{{ contribution.url | truncatechars:60 }}</a>
                        </div>
                        <div style="margin: 10px">
                            <p>Descripción:<br>{{contribution.description}}</p>

                           {{ contribution.html | safe }}
                        </div>
                        <figcaption style="margin: 10px;" class="figure-caption">
                            <div class="row">
                                <div class="col-8">
                                    {{ contribution.user_voted.value_vote }}

                                    <span style="color: green">({{ contribution.like }})</span>
                                    {% if contribution.user_voted and contribution.user_voted.value_vote == 1 %}
                                        <a class="btn btn-rounded btn-success" style="margin: 5px;" disabled="disabled">
                                            <i class="fas fa-thumbs-up"></i>
                                        </a>
                                    {% else %}
                                        <a class="btn btn-rounded btn-default" style="margin: 5px;"
                                            {% if vote_user_id %}
                                                href="{% url 'contributions:vote_contribution' id_contribution=contribution.id value=1 %}?redirect={% url 'contributions:home' %}"
                                            {% else %}
                                                disabled="disabled"
                                            {% endif %}
                                        >
                                            <i class="fas fa-thumbs-up"></i>
                                        </a>
                                    {% endif %}

                                    <span style="color: red">({{ contribution.unlike }})</span>
                                    {% if contribution.user_voted and contribution.user_voted.value_vote == 0 %}
                                        <a class="btn btn-rounded btn-danger" style="margin: 5px;" disabled="disabled">
                                            <i class="fas fa-thumbs-down"></i>
                                        </a>
                                    {% else %}
                                        <a class="btn btn-rounded btn-default" style="margin: 5px;"
                                            {% if vote_user_id %}
                                                href="{% url 'contributions:vote_contribution' id_contribution=contribution.id value=0 %}?redirect={% url 'contributions:home' %}"
                                            {% else %}
                                                disabled="disabled"
                                            {% endif %}
                                        >
                                            <i class="fas fa-thumbs-down"></i>
                                        </a>
                                    {% endif %}
                                </div>
                                <p>Número de comentarios: {{ contribution.num_comments}}</p>
                                <div class="col-4">
                                    Compartido por: {{ contribution.author_username }}
                                </div>
                            </div>


                        </figcaption>
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="col-5">
            {% if new_contribution_form %}
                <div class="col-12">

                    <div class="card">
                        <h5 class="card-header">Añadir contribucion
                            <a class="btn btn-info" href="{% url 'contributions:user_page' id_user=vote_user_id %}">Ir a mi página</a>
                        </h5>
                        <div class="card-body">
                            <form method="post" action="">
                                {% csrf_token %}

                                {{ new_contribution_form.non_field_errors }}

                                {% for hidden_field in new_contribution_form.hidden_fields %}
                                    {{ hidden_field.errors }}
                                    {{ hidden_field }}
                                {% endfor %}

                                {% for field in new_contribution_form.visible_fields %}
                                    <div class="form-group">
                                        <label for="" class="col-form-label col-12">{{ field.label_tag }}</label>
                                        {{ field.errors }}
                                        {{ field }}
                                        <div>
                                            {{ field.help_text }}
                                        </div>
                                    </div>
                                {% endfor %}

                                <button type="submit" class="btn btn-success">Contribuir</button>

                            </form>
                        </div>
                    </div>
                </div>
            {% else %}
                <p> Debes estar autenticado para poder añadir contribuciones</p>
            {% endif %}

            {% if last_user_contributions %}
                {% for contribution in last_user_contributions %}
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <a href="{% url 'contributions:single_contribution' id_contribution=contribution.id %}">
                                    <h3 class="card-title">{{ contribution.name }}</h3>
                                </a>
                                <a href="{{ contribution.url }}" class="btn btn-primary">{{ contribution.url |truncatechars:60 }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p> Debes estar autenticado para poder visualizar tus contribuciones</p>
            {% endif %}

        </div>
    </div>




{% endblock body %}

templates/contribution/information_page.html
{% extends "base/base.html" %}

{% block body %}

<h1> {{author}}</h1>

<p>
    {{object}}
</p>

<p>
    {{fuctionality}}
</p>
{% endblock body %}

templates/contribution/single_contribution.html
{% extends "base/base.html" %}

{% block body %}
<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">
                    <a href="{% url 'contributions:single_contribution' id_contribution=contribution.id %}">
                        {{ contribution.name }}
                    </a>
                    <span style="float: right"> {{ contribution.date |date:"d/m/Y H:i" }}</span>
                </h3>
                <a href="{{ contribution.url }}" class="btn btn-primary">{{ contribution.url }}</a>
            </div>
            <div style="margin: 10px">
                <p>Descripción:<br>{{contribution.description}}</p>
               {{ contribution.html | safe }}
            </div>
            <figcaption style="margin: 10px;" class="figure-caption">
                <div class="row">
                    <div class="col-8">
                        

                        <span style="color: green">({{ contribution.like }})</span>
                        {% if contribution.user_voted and contribution.user_voted.value_vote == 1 %}
                            <a class="btn btn-rounded btn-success" style="margin: 5px;" disabled="disabled">
                                <i class="fas fa-thumbs-up"></i>
                            </a>
                        {% else %}
                            <a class="btn btn-rounded btn-default" style="margin: 5px;"
                                {% if vote_user_id %}
                                    href="{% url 'contributions:vote_contribution' id_contribution=contribution.id value=1 %}?redirect={% url 'contributions:single_contribution' id_contribution=contribution.id %}"
                                {% else %}
                                    disabled="disabled"
                                {% endif %}
                            >
                                <i class="fas fa-thumbs-up"></i>
                            </a>
                        {% endif %}

                        <span style="color: red">({{ contribution.unlike }})</span>
                        {% if contribution.user_voted and contribution.user_voted.value_vote == 0 %}
                            <a class="btn btn-rounded btn-danger" style="margin: 5px;" disabled="disabled">
                                <i class="fas fa-thumbs-down"></i>
                            </a>
                        {% else %}
                            <a class="btn btn-rounded btn-default" style="margin: 5px;"
                                {% if vote_user_id %}
                                    href="
                                    {% url 'contributions:vote_contribution' id_contribution=contribution.id value=0 %}?redirect={% url 'contributions:single_contribution' id_contribution=contribution.id %}"
                                {% else %}
                                    disabled="disabled"
                                {% endif %}
                            >
                                <i class="fas fa-thumbs-down"></i>
                            </a>
                        {% endif %}
                    </div>
                    <p>Numero de comentarios: {{contribution.num_comments}}</p>
                    <div class="col-4">
                        Compartido por: {{ contribution.author_username }}
                    </div>
                </div>
            </figcaption>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <h5 class="card-header">Comentarios
                            <a class="btn btn-info" href="{% url 'contributions:download_comments' id_contribution=contribution.id %}">
                                Descargar comentarios en xml
                            </a>
                            <a class="btn btn-info" href="{% url 'contributions:download_comments' id_contribution=contribution.id %}?format=json">
                                Descargar comentarios en json
                            </a>
                        </h5>

                        <div class="card-body">
                            <div class="list-group">
                                {% for comment in contribution.comments %}
                                <div class="d-flex w-100 justify-content-between">
                                    <a style="margin: 5px;" href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                                        <strong>{{comment.author.username}}</strong> | <small>{{ comment.date }}</small>
                                            <p class="mb-1">
                                                {{ comment.text }}
                                            </p>
                                        </a>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        {% if new_comment_form %}
            <div class="col-12">

                <div class="card">
                    <h5 class="card-header">Añadir comentario</h5>
                    <div class="card-body">
                        <form method="post" action="">
                            {% csrf_token %}

                            {{ new_comment_form.non_field_errors }}

                            {% for hidden_field in new_comment_form.hidden_fields %}
                                {{ hidden_field.errors }}
                                {{ hidden_field }}
                            {% endfor %}

                            {% for field in new_comment_form.visible_fields %}
                                <div class="form-group">
                                    <label for="" class="col-form-label">{{ field.label_tag }}</label>
                                    {{ field.errors }}
                                    {{ field }}
                                    {{ field.help_text }}
                                </div>
                            {% endfor %}

                            <button type="submit" class="btn btn-success">Comentar</button>

                        </form>
                    </div>
                </div>
            </div>
        {% else %}
            <p> Debes estar autenticado para poder comentar</p>
        {% endif %}
    </div>

</div>


{% endblock body %}

templates/contribution/user_page.html
{% extends "base/base.html" %}

{% block body %}

<div class="row">
    <div class="col-4">
        {% for contribution in contributions %}
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'contributions:single_contribution' id_contribution=contribution.id %}">
                            <h3 class="card-title">{{ contribution.name }}</h3>
                        </a>
                        <a href="{{ contribution.url }}" class="btn btn-primary">{{ contribution.url|truncatechars:30 }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-4">
        {% for comment in comments %}
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5>Comentario:  </h5>
                        <p>{{ comment.text }}</p>
                        <h5> En la publicación:</h5>
                        <a href="{% url 'contributions:single_contribution' id_contribution=comment.id_contribution %}">
                            <h3 class="card-title">{{ comment.name_contribution }}</h3>
                        </a>
                        <a href="{{ comment.url_contribution }}" class="btn btn-primary">{{ comment.url_contribution |truncatechars:40}}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-4">
        {% for vote in votes %}
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5>Voto:  </h5>
                        <p>{% if vote.value_vote == 1 %} Voto positivo {% else %} Voto negativo {% endif %}</p>
                        <h5> En la publicación:</h5>
                        <a href="{% url 'contributions:single_contribution' id_contribution=vote.id_contribution %}">
                            <h3 class="card-title">{{ vote.name_contribution }}</h3>
                        </a>
                        <a href="{{ vote.url_contribution }}" class="btn btn-primary">{{ vote.url_contribution |truncatechars:40}}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


</div>



{% endblock body %}